workspace_url: https://adb-984752964297111.11.azuredatabricks.net/
lakebase_dsn: ''
lakebase_host: instance-4abc793a-34e7-49ea-aec3-e35f9ebefb2e.database.azuredatabricks.net
registry_schema: agent_registry
catalog: shm
lakebase_instance_name: agent-registry
lakebase_capacity: CU_1
lakebase_retention_days: 7
lakebase_user: ''
lakebase_db: databricks_postgres
